-- Seed template assets for Kolabs CMS
-- Safe to run multiple times (upsert by slug)

insert into public.items (
  type,
  title,
  slug,
  status,
  one_liner,
  hero_image,
  tags,
  cta_type,
  cta_url,
  featured,
  published,
  published_at,
  proof_cue,
  decision_md,
  inputs_md,
  output_md,
  confidence_md,
  impact_md,
  deleted_at
)
values
(
  'Tool',
  'Site Yield Simulator',
  'site-yield-simulator',
  'Proven',
  'Calculate maximum permissible yield and financial viability for urban infill plots.',
  null,
  array['land', 'capital', 'urban'],
  'Try',
  '#',
  true,
  true,
  '2024-05-12T10:00:00Z',
  '15% ROI uplift identified',
  'Should we acquire this plot at the asking price based on maximum allowable density?',
  'Plot boundaries (GeoJSON), local zoning codes, current construction costs, target IRR.',
  'Interactive 3D massing model, financial pro-forma, and risk matrix.',
  'High for residential use cases. Commercial yields require manual adjustment for local vacancy rates.',
  'Reduced feasibility study time from 3 weeks to 4 hours. Identified 15% ROI uplift on average.',
  null
),
(
  'Case',
  'Masterplan Optimization for SOE',
  'masterplan-optimization-soe',
  'Proven',
  'Restructured a 500-hectare masterplan to align with new mobility corridors.',
  null,
  array['infra', 'mobility', 'governance'],
  'Read',
  '#',
  true,
  true,
  '2024-04-20T10:00:00Z',
  'Saved $40M in infrastructure costs',
  'How to phase infrastructure deployment to minimize upfront capital while maximizing early land value?',
  'Existing masterplan CAD, regional transit plans, phased capital budget constraints.',
  'Revised phasing strategy, updated land use mix, and infrastructure deployment schedule.',
  'Validated by third-party engineering review. Subject to municipal approval timelines.',
  'Saved $40M in upfront infrastructure costs and accelerated phase 1 revenue by 18 months.',
  null
),
(
  'Brief',
  'The AI-Augmented Developer',
  'ai-augmented-developer',
  'Method',
  'How generative models are compressing the design-to-development lifecycle.',
  null,
  array['capital', 'governance'],
  'Download',
  '#',
  false,
  true,
  '2024-06-01T10:00:00Z',
  '12-page executive memo',
  'Where should real estate developers invest in AI capabilities today to build a competitive moat?',
  'Interviews with 20+ GCC developers, analysis of 50+ proptech startups, internal Kolabs experiments.',
  'Strategic memo detailing a 3-horizon adoption framework for AI in real estate.',
  'Horizon 1 and 2 are highly actionable. Horizon 3 remains speculative.',
  'Adopted by 3 master developers to guide their 2025 digital transformation budgets.',
  null
),
(
  'Research',
  'Algorithmic Zoning Analysis',
  'algorithmic-zoning-analysis',
  'Experiment',
  'Extracting implicit zoning rules from historical building permit data using LLMs.',
  null,
  array['land', 'governance'],
  'Read',
  '#',
  true,
  true,
  '2024-06-15T10:00:00Z',
  'Published in Urban Tech Journal',
  'Can we predict zoning variance approvals based on historical precedent?',
  '10 years of municipal building permits, NLP extraction of variance justifications.',
  'Predictive model scoring the likelihood of variance approval for new proposals.',
  'Model achieves 78% accuracy on historical holdout set. Not yet tested in live applications.',
  'Demonstrates the potential to quantify regulatory risk in early-stage land acquisition.',
  null
),
(
  'Tool',
  'Carbon Cost Estimator',
  'carbon-cost-estimator',
  'Method',
  'Translate early-stage design decisions into embodied carbon and financial cost.',
  null,
  array['infra', 'capital'],
  'Request',
  '#',
  false,
  true,
  '2024-05-28T10:00:00Z',
  'Integrates with Revit & Rhino',
  'Which structural system offers the best balance of cost and embodied carbon?',
  'Basic massing, structural system selection, local material availability.',
  'Comparative dashboard showing CapEx vs. Embodied Carbon trade-offs.',
  'Estimates are +/- 20% accurate at concept stage. Requires detailed LCA for compliance.',
  'Enabled a client to reduce embodied carbon by 12% with zero cost premium on a commercial tower.',
  null
),
(
  'Case',
  'Transit-Oriented Development Strategy',
  'tod-strategy',
  'Proven',
  'Optimizing land value capture around a new light rail network.',
  null,
  array['land', 'mobility', 'capital'],
  'Read',
  '#',
  false,
  true,
  '2024-03-10T10:00:00Z',
  '22% increase in projected land value',
  'How to zone station-adjacent parcels to maximize long-term value capture?',
  'Transit alignment, ridership projections, current land ownership, market absorption rates.',
  'Zoning recommendations, value capture mechanisms, and implementation roadmap.',
  'Highly dependent on timely delivery of the transit infrastructure.',
  'Projected a 22% increase in land value capture over the baseline scenario.',
  null
)
on conflict (slug)
do update set
  type = excluded.type,
  title = excluded.title,
  status = excluded.status,
  one_liner = excluded.one_liner,
  hero_image = excluded.hero_image,
  tags = excluded.tags,
  cta_type = excluded.cta_type,
  cta_url = excluded.cta_url,
  featured = excluded.featured,
  published = excluded.published,
  published_at = excluded.published_at,
  proof_cue = excluded.proof_cue,
  decision_md = excluded.decision_md,
  inputs_md = excluded.inputs_md,
  output_md = excluded.output_md,
  confidence_md = excluded.confidence_md,
  impact_md = excluded.impact_md,
  deleted_at = null,
  updated_at = now();
